data:
    raw:
        file1: "../data/raw/marketing_campaign.csv"
    clean:
        file1: "../data/clean/marketing_campaign.csv"
        file2: "../data/clean/bank-full.csv"
        file3: "../data/clean/CP_ready_to_model.csv"
        file4: "../data/clean/data_w_cluster.csv"