data:
    raw:
        file1: "../data/raw/LeadScoring.csv"
        file2: "../data/raw/Leads_Data_Dictionary.csv"
        file3: "../data/raw/digital_marketing_campaign_dataset.csv"
        file4: "../data/raw/bank.csv"
        file5: "../data/raw/bank-full.csv"
        file6: "../data/raw/bank-additional.csv"
        file7: "../data/raw/bank-additional-full.csv"
    clean:
        file1: "../data/clean/leadscoring.csv"
        file2: "../data/clean/bank-full.csv"
        file3: "../data/clean/ready_to_model.csv"