[project]
name = "final-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=5.0.0",
    "hdbscan>=0.8.44",
    "imblearn>=0.0",
    "jupyter>=1.1.1",
    "mlstatkit>=0.1.91",
    "pandas>=3.0.3",
    "pathlib>=1.0.1",
    "permetrics==2.0.0",
    "plotly>=6.8.0",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "streamlit>=1.58.0",
    "xgboost>=3.3.0",
]
